$ ->
  ranges = gon.ranges
  averages = gon.average_hours
  overall_average = gon.main_average
  ranges1 = gon.ranges1
  averages1 = gon.average_hours1
  overall_average1 = gon.main_average1
  ranges2 = gon.ranges2
  averages2 = gon.average_hours2
  overall_average2 = gon.main_average2

  chart = new Highcharts.Chart
    chart: renderTo: 'chart'
    title: text: 'Time in Berth'
    xAxis: type: 'datetime'
    yAxis: title: text: null
    tooltip:
      crosshairs: true
      shared: true
      valueSuffix: 'h'
    legend: {}
    series: [
      {
        name: 'Average Duration by Month (0 Incident)'
        data: averages
        zIndex: 1
        marker:
          fillColor: 'white'
          lineWidth: 2
          lineColor: Highcharts.getOptions().colors[0]
      }
      {
        name: 'Range'
        data: ranges
        type: 'arearange'
        lineWidth: 0
        linkedTo: ':previous'
        color: Highcharts.getOptions().colors[0]
        fillOpacity: 0.3
        zIndex: 0
      }
      {
        name: 'Overall Average Duration'
        data: overall_average
        type: 'line'
        lineWidth: 1
        # marker: enabled: false 
        color: Highcharts.getOptions().colors[3]
        # enableMouseTracking: false
        zIndex: 3
      }
    ]


  $('#action1').click (e) ->
    $('.show1').slideDown().addClass('highlight')
    $('#panel-delay').removeClass('panel-green').addClass('panel-red').find('.huge').text('30min')
    $('#panel-eut .huge').text('9:30pm')

  $('#action2').click (e) ->
    chart.addSeries
      name: 'Average Duration by Month (1 Incident)'
      data: averages1
      zIndex: 3
      color: Highcharts.getOptions().colors[0]
      marker:
        fillColor: 'white'
        lineWidth: 2
        lineColor: Highcharts.getOptions().colors[0]
    chart.addSeries
      name: 'Range (1 Incident)'
      data: ranges1
      type: 'arearange'
      lineWidth: 0
      linkedTo: ':previous'
      color: Highcharts.getOptions().colors[0]
      fillOpacity: 0.3
      zIndex: 0
    chart.addSeries
      name: 'Overall Average Duration (1 Incident)'
      data: overall_average1
      type: 'line'
      lineWidth: 1
      # marker: enabled: false 
      color: Highcharts.getOptions().colors[5]
      # enableMouseTracking: false
      zIndex: 3

    # chart.series[0].color = "#999"
    chart.series[0].update({color: '#999', marker: {lineColor: '#999'}}, false)
    # chart.series[2].options.color = "#3201D7"
    # chart.series[2].update(chart.series[2].options)
    chart.series[1].hide()
    $('.show2').slideDown().addClass('highlight')
    $('#panel-delay .huge').text('6h 30m')
    $('#panel-eut .huge').text('3:30am')
    $('#panel-incidents').removeClass('panel-green').addClass('panel-yellow')
    $('#panel-incidents .huge').text('1')
    $('#panel-records .huge').text(gon.records1)

  $('#action3').click (e) ->
    chart.addSeries
      name: 'Average Duration by Month (2 Incidents)'
      data: averages2
      zIndex: 3
      color: Highcharts.getOptions().colors[0]
      marker:
        fillColor: 'white'
        lineWidth: 2
        lineColor: Highcharts.getOptions().colors[0]
    chart.addSeries
      name: 'Range (2 Incidents)'
      data: ranges2
      type: 'arearange'
      lineWidth: 0
      linkedTo: ':previous'
      color: Highcharts.getOptions().colors[0]
      fillOpacity: 0.3
      zIndex: 0
    chart.addSeries
      name: 'Overall Average Duration (2 Incidents)'
      data: overall_average2
      type: 'line'
      lineWidth: 1
      # marker: enabled: false 
      color: Highcharts.getOptions().colors[5]
      # enableMouseTracking: false
      zIndex: 3

    chart.series[3].update({color: '#999', marker: {lineColor: '#999'}}, false)
    chart.series[4].hide()
    $('.show3').slideDown().addClass('highlight')
    $('#panel-delay .huge').text('11h 30m')
    $('#panel-eut .huge').text('8:30am')
    $('#panel-incidents .huge').text('2')
    $('#panel-records .huge').text(gon.records2)

  $('#panel-recommend').click (e) ->
    $(this).css('background-color', '#FFF662')
  
  
  

  
  
  
  

# ---
# generated by js2coffee 2.1.0