$ ->
  ranges = gon.ranges
  averages = gon.average_hours
  overall_average = [
    [
      1246406400000
      17
    ]
    [
      1248998400000
      17
    ]
  ]
  $('#chart').highcharts
    title: text: 'Time in Berth'
    xAxis: type: 'datetime'
    yAxis: title: text: null
    tooltip:
      crosshairs: true
      shared: true
      valueSuffix: 'h'
    legend: {}
    series: [
      {
        name: 'Average Duration by Month'
        data: averages
        zIndex: 1
        marker:
          fillColor: 'white'
          lineWidth: 2
          lineColor: Highcharts.getOptions().colors[0]
      }
      {
        name: 'Range'
        data: ranges
        type: 'arearange'
        lineWidth: 0
        linkedTo: ':previous'
        color: Highcharts.getOptions().colors[0]
        fillOpacity: 0.3
        zIndex: 0
      }
      # {
      #   name: 'Overall Average Duration'
      #   data: overall_average
      #   type: 'line'
      #   lineWidth: 1
      #   marker: enabled: false 
      #   color: Highcharts.getOptions().colors[3]
      #   enableMouseTracking: false
      #   zIndex: 3
      # }
    ]
  return

# ---
# generated by js2coffee 2.1.0